import { Router } from "express";
import { allow, authenticate, internalRoles } from "../middlewares/auth.js";
import { ROLES } from "../constants/workflow.js";
import { internalLimiter } from "./limits.js";
import authRoutes from "./auth.routes.js";
import publicRoutes from "./public.routes.js";
import analyticsRoutes from "./analytics.routes.js";
import usersRoutes from "./users.routes.js";
import branchesRoutes from "./branches.routes.js";
import customersRoutes from "./customers.routes.js";
import shipmentsRoutes from "./shipments.routes.js";
import tmsRoutes from "./tms.routes.js";
import payslipsRoutes from "./payslips.routes.js";
import onboardingRoutes from "./onboarding.routes.js";
import expansionRoutes from "./expansion.routes.js";
import bookingRoutes from "./booking.routes.js";
import vendorPortalRoutes from "./vendor-portal.routes.js";
import notificationRoutes from "./notification.routes.js";
import pickupRequestRoutes from "./pickup-request.routes.js";
import pickupRunSheetRoutes from "./pickup-run-sheet.routes.js";
const router = Router();
router.use(authRoutes, publicRoutes);
router.use(authenticate, internalRoles, internalLimiter);
router.use(usersRoutes, payslipsRoutes, onboardingRoutes, branchesRoutes, vendorPortalRoutes);
router.use(allow(ROLES.ADMIN, ROLES.MANAGER, ROLES.EMPLOYEE));
router.use(analyticsRoutes, customersRoutes, shipmentsRoutes, tmsRoutes, expansionRoutes, bookingRoutes, pickupRequestRoutes, pickupRunSheetRoutes, notificationRoutes);
export default router;
