import { Router } from "express";
import { authenticate, internalRoles } from "../middlewares/auth.js";
import { internalLimiter } from "./limits.js";
import authRoutes from "./auth.routes.js";
import publicRoutes from "./public.routes.js";
import analyticsRoutes from "./analytics.routes.js";
import usersRoutes from "./users.routes.js";
import branchesRoutes from "./branches.routes.js";
import customersRoutes from "./customers.routes.js";
import shipmentsRoutes from "./shipments.routes.js";
import tmsRoutes from "./tms.routes.js";
const router = Router();
router.use(authRoutes, publicRoutes);
router.use(authenticate, internalRoles, internalLimiter);
router.use(analyticsRoutes, usersRoutes, branchesRoutes, customersRoutes, shipmentsRoutes, tmsRoutes);
export default router;
