export const ROLES = Object.freeze({ ADMIN: "ADMIN", MANAGER: "MANAGER", EMPLOYEE: "EMPLOYEE", HR: "HR", VENDOR: "VENDOR" });
export const ACTIVE = Object.freeze({ ACTIVE: "ACTIVE", INACTIVE: "INACTIVE" });
export const SHIPMENT_STATUS = Object.freeze({
  BOOKED: "BOOKED",
  IN_TRANSIT: "IN_TRANSIT",
  RECEIVED: "RECEIVED",
  LR_IMAGE_UPLOADED: "LR_IMAGE_UPLOADED",
  LR_IMAGE_VERIFIED: "LR_IMAGE_VERIFIED",
  COMPLETED: "COMPLETED",
  CLOSED: "CLOSED",
  CANCELLED: "CANCELLED",
});
export const TRACKING_EVENT_STATUS = Object.freeze({
  ...SHIPMENT_STATUS,
  SEGREGATED: "SEGREGATED",
  MANIFESTED: "MANIFESTED",
  PICKED_UP: "PICKED_UP",
  AT_HUB: "AT_HUB",
  DELIVERED: "DELIVERED",
  EXCEPTION: "EXCEPTION",
  MONEY_RECEIPT_CREATED: "MONEY_RECEIPT_CREATED",
  TRIP_PLANNED: "TRIP_PLANNED",
  OUT_FOR_DELIVERY: "OUT_FOR_DELIVERY",
  POD_UPLOADED: "POD_UPLOADED",
  DRS_CLOSED: "DRS_CLOSED",
});
export const DOCUMENT_STATUS = Object.freeze({
  PENDING: "PENDING",
  VERIFIED: "VERIFIED",
  REJECTED: "REJECTED",
});
export const TRANSITIONS = Object.freeze({
  BOOKED: [SHIPMENT_STATUS.IN_TRANSIT, SHIPMENT_STATUS.CANCELLED],
  IN_TRANSIT: [SHIPMENT_STATUS.RECEIVED, SHIPMENT_STATUS.CANCELLED],
  RECEIVED: [SHIPMENT_STATUS.LR_IMAGE_UPLOADED],
  LR_IMAGE_UPLOADED: [SHIPMENT_STATUS.LR_IMAGE_VERIFIED, SHIPMENT_STATUS.RECEIVED],
  LR_IMAGE_VERIFIED: [SHIPMENT_STATUS.COMPLETED],
  COMPLETED: [SHIPMENT_STATUS.CLOSED],
  CLOSED: [],
  CANCELLED: [],
});
