export const ROLES = Object.freeze({ ADMIN: "ADMIN", EMPLOYEE: "EMPLOYEE" });
export const ACTIVE = Object.freeze({ ACTIVE: "ACTIVE", INACTIVE: "INACTIVE" });
export const SHIPMENT_STATUS = Object.freeze({
  BOOKED: "BOOKED",
  IN_TRANSIT: "IN_TRANSIT",
  RECEIVED: "RECEIVED",
  LR_IMAGE_UPLOADED: "LR_IMAGE_UPLOADED",
  LR_IMAGE_VERIFIED: "LR_IMAGE_VERIFIED",
  COMPLETED: "COMPLETED",
  CLOSED: "CLOSED",
  CANCELLED: "CANCELLED",
});
export const DOCUMENT_STATUS = Object.freeze({
  PENDING: "PENDING",
  VERIFIED: "VERIFIED",
  REJECTED: "REJECTED",
});
export const TRANSITIONS = Object.freeze({
  BOOKED: [SHIPMENT_STATUS.IN_TRANSIT, SHIPMENT_STATUS.CANCELLED],
  IN_TRANSIT: [SHIPMENT_STATUS.RECEIVED, SHIPMENT_STATUS.CANCELLED],
  RECEIVED: [SHIPMENT_STATUS.LR_IMAGE_UPLOADED],
  LR_IMAGE_UPLOADED: [SHIPMENT_STATUS.LR_IMAGE_VERIFIED, SHIPMENT_STATUS.RECEIVED],
  LR_IMAGE_VERIFIED: [SHIPMENT_STATUS.COMPLETED],
  COMPLETED: [SHIPMENT_STATUS.CLOSED],
  CLOSED: [],
  CANCELLED: [],
});
